import type { Metadata } from 'next'
import { AppContextProvider, Header } from '@components'
import { Kumbh_Sans } from 'next/font/google'
import '@styles/main.scss'
import styles from './layout.module.scss'

const font = Kumbh_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${styles.layout} ${font.className}`}>
        <AppContextProvider>
          <Header />
          <div className={styles.content}>
            {children}
          </div>
        </AppContextProvider>
      </body>
    </html>
  )
}
